/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAbout {
        "nice": string;
    }
    interface AppHello {
    }
    interface AppSekolah {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppHelloElement extends Components.AppHello, HTMLStencilElement {
    }
    var HTMLAppHelloElement: {
        prototype: HTMLAppHelloElement;
        new (): HTMLAppHelloElement;
    };
    interface HTMLAppSekolahElement extends Components.AppSekolah, HTMLStencilElement {
    }
    var HTMLAppSekolahElement: {
        prototype: HTMLAppSekolahElement;
        new (): HTMLAppSekolahElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-hello": HTMLAppHelloElement;
        "app-sekolah": HTMLAppSekolahElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
        "nice"?: string;
    }
    interface AppHello {
    }
    interface AppSekolah {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-hello": AppHello;
        "app-sekolah": AppSekolah;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-hello": LocalJSX.AppHello & JSXBase.HTMLAttributes<HTMLAppHelloElement>;
            "app-sekolah": LocalJSX.AppSekolah & JSXBase.HTMLAttributes<HTMLAppSekolahElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
